# Generated by Django 3.0.3 on 2020-03-07 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0006_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='pessoa',
            new_name='comen',
        ),
        migrations.AddField(
            model_name='comentario',
            name='pessoas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_noticias.Pessoa'),
        ),
    ]
