# Generated by Django 3.0.3 on 2020-03-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0007_auto_20200306_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comen',
            new_name='noticia',
        ),
    ]
